# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout
      - run: mkdir /tmp/helm-preprocessor/
      - run: dotnet publish --runtime linux-x64 -c release /p:PublishSingleFile=true  -o /tmp/helm-preprocessor /p:AssemblyName=helm-preprocessor-linux-x64 /p:Version=${CIRCLE_TAG:-"0.1.0"}
      - run: dotnet publish --runtime win-x64 -c release /p:PublishSingleFile=true  -o /tmp/helm-preprocessor /p:AssemblyName=helm-preprocessor-win-x64 /p:Version=${CIRCLE_TAG:-"0.1.0"}
      - run: dotnet publish --runtime osx-x64 -c release /p:PublishSingleFile=true  -o /tmp/helm-preprocessor /p:AssemblyName=helm-preprocessor-osx-x64 /p:Version=${CIRCLE_TAG:-"0.1.0"}
      - persist_to_workspace:
          root: /tmp/helm-preprocessor/
          paths:
            - linux-x64/helm-preprocessor
        
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./artifacts/helm-preprocessor-linux-x64 --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
          
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/

      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/